version: "3"
services:
    web:
        build: .
        ports:
            - "8000:80"
        depends_on:
            - db
    db:
        ports:
            - "1433:1433"
        image: "microsoft/mssql-server-linux"
        environment:
            SA_PASSWORD: "Teste@123"
            ACCEPT_EULA: "Y"